# Generated by Django 4.0.3 on 2023-04-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_alter_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
