# Generated by Django 4.0.3 on 2023-04-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_automobilevo_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='available',
        ),
    ]
