# Generated by Django 4.0.3 on 2023-04-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='employee_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
