# Generated by Django 4.0.3 on 2023-04-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_technician_options_remove_appointment_vin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='auto',
            new_name='vin',
        ),
    ]
