# Generated by Django 4.0.3 on 2023-04-25 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_remove_appointment_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='auto_vin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auto_vin', to='service_rest.automobilevo'),
            preserve_default=False,
        ),
    ]
