# Generated by Django 4.0.3 on 2023-04-25 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_appointment_auto_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='auto_vin',
            new_name='vin',
        ),
    ]
