# Generated by Django 4.0.3 on 2023-04-26 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0012_remove_appointment_date_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('vin',)},
        ),
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ('employee_id',)},
        ),
    ]
