# Generated by Django 4.0.3 on 2023-04-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0013_alter_appointment_options_alter_technician_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='sold',
        ),
    ]
