# Generated by Django 4.0.3 on 2023-04-27 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0015_alter_appointment_options_remove_appointment_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='automobile',
        ),
        migrations.AddField(
            model_name='appointment',
            name='sold',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vip', to='service_rest.automobilevo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='vin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auto_vin', to='service_rest.automobilevo'),
            preserve_default=False,
        ),
    ]
